package view;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author EmanuelHurt
 */

public class ControlPanel extends javax.swing.JPanel {
    
    private Color enterColor;
    
    public ControlPanel() {
        initComponents();
        enterColor = new Color(204,204,204);
    }

    public JLabel getBtnBuys() {
        return btnBuys;
    }

    public JLabel getBtnNewSale() {
        return btnNewSale;
    }

    public JLabel getBtnProductsList() {
        return btnProductsList;
    }
    
    public JTable getTblProductsToExpire() {
        return tblProductsToExpire;
    }
    
    public JTable getTblMinimum() {
        return tblMinimum;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        salesTopPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMinimum = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductsToExpire = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnBuys = new javax.swing.JLabel();
        btnNewSale = new javax.swing.JLabel();
        btnProductsList = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 242, 247));
        setLayout(new java.awt.GridBagLayout());

        salesTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        salesTopPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        tblMinimum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblMinimum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROVEEDOR", "PRODUCTO", "FORMA", "SALDO", "VENCIMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMinimum);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PRODUCTOS CON SALDO MÍNIMO");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 204, 255)));
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout salesTopPanelLayout = new javax.swing.GroupLayout(salesTopPanel);
        salesTopPanel.setLayout(salesTopPanelLayout);
        salesTopPanelLayout.setHorizontalGroup(
            salesTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
            .addGroup(salesTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        salesTopPanelLayout.setVerticalGroup(
            salesTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesTopPanelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 197;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 20, 5, 0);
        add(salesTopPanel, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        tblProductsToExpire.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblProductsToExpire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROVEEDOR", "PRODUCTO", "FORMA", "SALDO", "VENCIMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProductsToExpire);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VENCIMIENTOS PRÓXIMOS");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 204, 255)));
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 222;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 37, 5, 39);
        add(jPanel2, gridBagConstraints);

        btnBuys.setBackground(new java.awt.Color(255, 255, 255));
        btnBuys.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnBuys.setForeground(new java.awt.Color(51, 51, 51));
        btnBuys.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconProducto.png"))); // NOI18N
        btnBuys.setText("Ingreso Producto");
        btnBuys.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        btnBuys.setIconTextGap(10);
        btnBuys.setOpaque(true);
        btnBuys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuysMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 60, 0, 0);
        add(btnBuys, gridBagConstraints);

        btnNewSale.setBackground(new java.awt.Color(255, 255, 255));
        btnNewSale.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnNewSale.setForeground(new java.awt.Color(51, 51, 51));
        btnNewSale.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNewSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconVender.png"))); // NOI18N
        btnNewSale.setText("Nueva Venta");
        btnNewSale.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        btnNewSale.setIconTextGap(15);
        btnNewSale.setOpaque(true);
        btnNewSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewSaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewSaleMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 20, 0, 0);
        add(btnNewSale, gridBagConstraints);

        btnProductsList.setBackground(new java.awt.Color(255, 255, 255));
        btnProductsList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProductsList.setForeground(new java.awt.Color(51, 51, 51));
        btnProductsList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconProductsList.png"))); // NOI18N
        btnProductsList.setText("Productos");
        btnProductsList.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        btnProductsList.setOpaque(true);
        btnProductsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductsListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductsListMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 49, 0, 0);
        add(btnProductsList, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewSaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewSaleMouseEntered
        btnNewSale.setBackground(enterColor);
    }//GEN-LAST:event_btnNewSaleMouseEntered

    private void btnNewSaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewSaleMouseExited
        btnNewSale.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnNewSaleMouseExited

    private void btnBuysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuysMouseEntered
        btnBuys.setBackground(enterColor);
    }//GEN-LAST:event_btnBuysMouseEntered

    private void btnBuysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuysMouseExited
        btnBuys.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnBuysMouseExited

    private void btnProductsListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsListMouseEntered
        btnProductsList.setBackground(enterColor);
    }//GEN-LAST:event_btnProductsListMouseEntered

    private void btnProductsListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsListMouseExited
        btnProductsList.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnProductsListMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuys;
    private javax.swing.JLabel btnNewSale;
    private javax.swing.JLabel btnProductsList;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel salesTopPanel;
    private javax.swing.JTable tblMinimum;
    private javax.swing.JTable tblProductsToExpire;
    // End of variables declaration//GEN-END:variables
}
