package view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author EmanuelHurt
 */
public class InitialWindow extends javax.swing.JFrame {
    
    public InitialWindow() {       
        
        initComponents();
        
        //putHoverEffectSideButtons();
    }
    
    public void changeCenterPanel(JPanel panel) {
        centerPanel.setVisible(false);
        majorPanel.remove(centerPanel);
        majorPanel.add(panel, BorderLayout.CENTER);
        centerPanel = panel;
    }
    /*
    private void putHoverEffectSideButtons() {
        Color hoverColor = new Color(81, 81, 169);
        HoverEffect hoverSale = new HoverEffect(btnNewSale,hoverColor);
        btnNewSale.addMouseListener(hoverSale);
        
        HoverEffect hoverProducts = new HoverEffect(btnProducts, hoverColor);
        btnProducts.addMouseListener(hoverProducts);
        
        HoverEffect hoverProviders = new HoverEffect(lblBtnProviders, hoverColor);
        lblBtnProviders.addMouseListener(hoverProviders);
        
        HoverEffect hoverSettings = new HoverEffect(lblBtnSettings, hoverColor);
        lblBtnSettings.addMouseListener(hoverSettings);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        majorPanel = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        btnBuys = new javax.swing.JLabel();
        btnProducts = new javax.swing.JLabel();
        btnNewSale = new javax.swing.JLabel();
        btnControlPanel = new javax.swing.JLabel();
        lblBtnProviders = new javax.swing.JLabel();
        lblBtnSettings = new javax.swing.JLabel();
        lblBtnInputProducts = new javax.swing.JLabel();
        lblBtnSalesHistory = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        majorPanel.setLayout(new java.awt.BorderLayout());

        headPanel.setBackground(new java.awt.Color(169, 208, 134));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nombreFarmacia.png"))); // NOI18N
        jLabel4.setOpaque(true);

        lblDate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(241, 242, 247));
        lblDate.setText("08:39 Viernes 1 de Marzo");

        lblUser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(241, 242, 247));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("ADMINISTRADOR");

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblDate)
                        .addGap(0, 641, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblDate)
                .addGap(7, 7, 7)
                .addComponent(lblUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        majorPanel.add(headPanel, java.awt.BorderLayout.PAGE_START);

        sidePanel.setBackground(new java.awt.Color(18, 19, 130));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuys.setBackground(new java.awt.Color(18, 19, 130));
        btnBuys.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuys.setForeground(new java.awt.Color(169, 208, 134));
        btnBuys.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconAdd.png"))); // NOI18N
        btnBuys.setText("Agregar Producto");
        btnBuys.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnBuys.setIconTextGap(15);
        btnBuys.setOpaque(true);
        sidePanel.add(btnBuys, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 30));

        btnProducts.setBackground(new java.awt.Color(18, 19, 130));
        btnProducts.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProducts.setForeground(new java.awt.Color(169, 208, 134));
        btnProducts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconProducts.png"))); // NOI18N
        btnProducts.setText("Productos");
        btnProducts.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnProducts.setIconTextGap(15);
        btnProducts.setOpaque(true);
        sidePanel.add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 30));

        btnNewSale.setBackground(new java.awt.Color(18, 19, 130));
        btnNewSale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNewSale.setForeground(new java.awt.Color(169, 208, 134));
        btnNewSale.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNewSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconSale.png"))); // NOI18N
        btnNewSale.setText("Realizar Venta");
        btnNewSale.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnNewSale.setIconTextGap(15);
        btnNewSale.setOpaque(true);
        sidePanel.add(btnNewSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 30));

        btnControlPanel.setBackground(new java.awt.Color(18, 19, 130));
        btnControlPanel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnControlPanel.setForeground(new java.awt.Color(169, 208, 134));
        btnControlPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnControlPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconCentro.png"))); // NOI18N
        btnControlPanel.setText("Panel de Control");
        btnControlPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnControlPanel.setIconTextGap(15);
        btnControlPanel.setOpaque(true);
        sidePanel.add(btnControlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, 30));

        lblBtnProviders.setBackground(new java.awt.Color(18, 19, 130));
        lblBtnProviders.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnProviders.setForeground(new java.awt.Color(169, 208, 134));
        lblBtnProviders.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBtnProviders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconProvider.png"))); // NOI18N
        lblBtnProviders.setText("Proveedores");
        lblBtnProviders.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        lblBtnProviders.setIconTextGap(15);
        lblBtnProviders.setOpaque(true);
        sidePanel.add(lblBtnProviders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, 30));

        lblBtnSettings.setBackground(new java.awt.Color(18, 19, 130));
        lblBtnSettings.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnSettings.setForeground(new java.awt.Color(169, 208, 134));
        lblBtnSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBtnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconSettings.png"))); // NOI18N
        lblBtnSettings.setText("Configuraciones");
        lblBtnSettings.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        lblBtnSettings.setIconTextGap(15);
        lblBtnSettings.setOpaque(true);
        sidePanel.add(lblBtnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 180, -1));

        lblBtnInputProducts.setBackground(new java.awt.Color(18, 19, 130));
        lblBtnInputProducts.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnInputProducts.setForeground(new java.awt.Color(169, 208, 134));
        lblBtnInputProducts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBtnInputProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconArowR.png"))); // NOI18N
        lblBtnInputProducts.setText("Entradas de Producto");
        lblBtnInputProducts.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        lblBtnInputProducts.setIconTextGap(15);
        lblBtnInputProducts.setOpaque(true);
        sidePanel.add(lblBtnInputProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        lblBtnSalesHistory.setBackground(new java.awt.Color(18, 19, 130));
        lblBtnSalesHistory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnSalesHistory.setForeground(new java.awt.Color(169, 208, 134));
        lblBtnSalesHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBtnSalesHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconArowL.png"))); // NOI18N
        lblBtnSalesHistory.setText("Salidas de Producto");
        lblBtnSalesHistory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        lblBtnSalesHistory.setIconTextGap(15);
        lblBtnSalesHistory.setOpaque(true);
        sidePanel.add(lblBtnSalesHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, 30));

        majorPanel.add(sidePanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        majorPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(majorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(majorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblBtnControlPanel() {
        return btnControlPanel;
    }
    
    public JLabel getBtnProducts() {
        return btnProducts;
    }
    public JLabel getBtnBuys() {
        return btnBuys;
    }
    public JLabel getBtnNewSale() {
        return btnNewSale;
    }
    
    public JLabel getLblBtnSettings() {
        return lblBtnSettings;
    }
    
    public JLabel getLblBtnProviders() {
        return lblBtnProviders;
    }
    
    public JLabel getLblBtnInputProducts() {
        return lblBtnInputProducts;
    }
    
    public JLabel getLblDate() {
        return lblDate;
    }
    
    public JLabel getLblBtnSalesHistory() {
        return lblBtnSalesHistory;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuys;
    private javax.swing.JLabel btnControlPanel;
    private javax.swing.JLabel btnNewSale;
    private javax.swing.JLabel btnProducts;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel headPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBtnInputProducts;
    private javax.swing.JLabel lblBtnProviders;
    private javax.swing.JLabel lblBtnSalesHistory;
    private javax.swing.JLabel lblBtnSettings;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel majorPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
