package view;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.Window;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import java.util.GregorianCalendar;
import java.util.Calendar;
import javax.swing.JDialog;
import javax.swing.JTextField;

/**
 *
 * @author EmanuelHurt
 */
public class MyCalendar extends javax.swing.JPanel implements MouseListener {

    private JLabel[] dias;
    private int mes, anio;
    private final String[] nombresMeses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio",
                "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};;
    private final JDialog marco;
    private final JTextField campoFecha;
    
    public MyCalendar(JTextField campoFecha) {
        initComponents();      
        
        this.campoFecha = campoFecha;
        
        dias = new JLabel[42];
        
        GregorianCalendar calendario = new GregorianCalendar();
        mes = calendario.get(Calendar.MONTH); //obtenemos el mes actual
        anio = calendario.get(Calendar.YEAR); //obtenemos el anio actual
        
        crearEtiquetasDia();
        
        llenarCuerpo();
        //creación del marco que contendrá este panel
        Point puntoPantalla = campoFecha.getLocationOnScreen();
        //double xP = puntoPantalla.getX() + 100.0;
        marco = new JDialog();
        marco.setModal(true);
        marco.setLocation(puntoPantalla);
        marco.add(this);
        marco.setUndecorated(true);
        marco.pack();
        marco.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        lblMesAnio = new javax.swing.JLabel();
        lblBtnBack = new javax.swing.JLabel();
        lblBtnForward = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 242, 247));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 7));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Do");
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lu");
        jPanel2.add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ma");
        jPanel2.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mi");
        jPanel2.add(jLabel5);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ju");
        jPanel2.add(jLabel7);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vi");
        jPanel2.add(jLabel6);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sa");
        jPanel2.add(jLabel3);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMesAnio.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblMesAnio.setForeground(new java.awt.Color(51, 51, 51));
        lblMesAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesAnio.setText("Nombre del Mes Anio");

        lblBtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconBack.png"))); // NOI18N
        lblBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnBackMouseClicked(evt);
            }
        });

        lblBtnForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconForward.png"))); // NOI18N
        lblBtnForward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnForwardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBtnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMesAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBtnForward)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMesAnio)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblBtnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblBtnForward)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnBackMouseClicked
        mes --;
        if (mes < 0) {
            mes = 11;
            anio --;
        }
        rehacerEtiquetasDia();
        llenarCuerpo();
    }//GEN-LAST:event_lblBtnBackMouseClicked

    private void lblBtnForwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnForwardMouseClicked
        mes ++;
        if (mes > 11) {
            mes = 0;
            anio ++;
        }
        rehacerEtiquetasDia();
        llenarCuerpo();
    }//GEN-LAST:event_lblBtnForwardMouseClicked

    private void crearEtiquetasDia() {
        for (int i = 0; i < dias.length; i++) {
            JLabel dia = new JLabel();
            dia.setHorizontalAlignment(JLabel.CENTER);
            
            //dia.setOpaque(true);
            //dia.setBackground(Color.WHITE);
            //HoverEffect hover = new HoverEffect(dia,new Color(214, 234, 248 ));
            //dia.addMouseListener(hover);
            dias[i] = dia;
        }
    }
    
    private void rehacerEtiquetasDia() {
        for (int i = 0; i < dias.length; i++) {
            
            this.bodyPanel.remove(dias[i]);//limpiar el panel
            
            JLabel dia = new JLabel();
            dia.setHorizontalAlignment(JLabel.CENTER);
            dias[i] = dia;
        }
    }
    
    private void llenarCuerpo() {
        
        //datos del mes y el anio
        
        lblMesAnio.setText(nombresMeses[mes]+" "+anio);
        
        bodyPanel.setLayout(new GridLayout(6,7,0,0));
        
        GregorianCalendar calendario = new GregorianCalendar(anio,mes,1);
        
        int diaIniEnLaSemana = calendario.get(Calendar.DAY_OF_WEEK);
        int numDia = 1;
        int diasEnMes = calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
        
        for (int i = diaIniEnLaSemana - 1; numDia <= diasEnMes; i++) {
            dias[i].setText(numDia + "");
            dias[i].setOpaque(true);
            dias[i].setBackground(Color.WHITE);
            dias[i].addMouseListener(this);
            numDia ++;
        }
        
        for (int i = 0; i < dias.length; i++) {
            bodyPanel.add(dias[i]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBtnBack;
    private javax.swing.JLabel lblBtnForward;
    private javax.swing.JLabel lblMesAnio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        JLabel dia = (JLabel)e.getSource();
        String fecha;
        String sMes;
        String sDia;
        int numDia = Integer.parseInt(dia.getText());
        int nMes = mes+1;
        if (nMes < 10) {
            sMes = "0";
        }
        else {
            sMes = "";
        }
        
        if (numDia < 10) {
            sDia = "0";
        } else {
            sDia = "";
        }
        
        sMes = sMes + nMes;
        sDia = sDia + dia.getText();
        
        fecha = anio+"-"+sMes+"-"+sDia;
        
        this.campoFecha.setText(fecha);
        
        marco.dispose();
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {     
       //
    }

    @Override
    public void mouseEntered(MouseEvent e) {     
        JLabel lblDia = (JLabel)e.getSource();
        lblDia.setBackground(new Color(214, 234, 248));
    }

    @Override
    public void mouseExited(MouseEvent e) {
        JLabel lblDia = (JLabel)e.getSource();
        lblDia.setBackground(Color.WHITE);
    }
}
