package view;

import controller.ProductController;
import javax.swing.JDialog;

/**
 *
 * @author EmanuelHurt
 */
public class NameFileModal extends javax.swing.JPanel {

    private JDialog modalFrame;
    private ProductController productController;
    
    public NameFileModal(ProductController productController) {
        initComponents();
        
        this.productController = productController;
        
        modalFrame = new JDialog();
        modalFrame.setUndecorated(true);
        modalFrame.setModal(true);
        modalFrame.add(this);      
        modalFrame.pack();
        modalFrame.setLocationRelativeTo(null);
        modalFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblBtnCancel = new javax.swing.JLabel();
        lblBtnSave = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nombre del archivo:");

        txtFieldName.setColumns(15);
        txtFieldName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText(".xlsx");

        lblBtnCancel.setBackground(new java.awt.Color(204, 204, 204));
        lblBtnCancel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnCancel.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnCancel.setText("Cancelar");
        lblBtnCancel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnCancel.setOpaque(true);
        lblBtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnCancelMouseClicked(evt);
            }
        });

        lblBtnSave.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnSave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnSave.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnSave.setText("Guardar");
        lblBtnSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnSave.setOpaque(true);
        lblBtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnSaveMouseClicked
        String name = txtFieldName.getText();
        if (!name.isEmpty()) {
            productController.setNameToExportFile(name);
            modalFrame.dispose();
        }
    }//GEN-LAST:event_lblBtnSaveMouseClicked

    private void lblBtnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCancelMouseClicked
        modalFrame.dispose();
    }//GEN-LAST:event_lblBtnCancelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBtnCancel;
    private javax.swing.JLabel lblBtnSave;
    private javax.swing.JTextField txtFieldName;
    // End of variables declaration//GEN-END:variables
}
