package view;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author EmanuelHurt
 */
public class OptionsPurchasePanel extends javax.swing.JPanel {

    private Color enterColor;
    
    public OptionsPurchasePanel() {
        initComponents();
        enterColor = new Color(204,204,204);
    }

    public JLabel getLblBtnNewProduct() {
        return lblBtnNewProduct;
    }

    public JLabel getLblBtnRestock() {
        return lblBtnRestock;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblBtnRestock = new javax.swing.JLabel();
        lblBtnNewProduct = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 242, 247));
        setLayout(new java.awt.GridBagLayout());

        lblBtnRestock.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnRestock.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblBtnRestock.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnRestock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconRestock.png"))); // NOI18N
        lblBtnRestock.setText("Reposición de Producto");
        lblBtnRestock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        lblBtnRestock.setOpaque(true);
        lblBtnRestock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnRestockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnRestockMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 91, 0, 117);
        add(lblBtnRestock, gridBagConstraints);

        lblBtnNewProduct.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnNewProduct.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblBtnNewProduct.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconNewProduct.png"))); // NOI18N
        lblBtnNewProduct.setText("Nuevo Producto");
        lblBtnNewProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        lblBtnNewProduct.setOpaque(true);
        lblBtnNewProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnNewProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnNewProductMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 495;
        gridBagConstraints.ipady = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(72, 91, 42, 117);
        add(lblBtnNewProduct, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnRestockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnRestockMouseEntered
        lblBtnRestock.setBackground(enterColor);
    }//GEN-LAST:event_lblBtnRestockMouseEntered

    private void lblBtnRestockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnRestockMouseExited
        lblBtnRestock.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblBtnRestockMouseExited

    private void lblBtnNewProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnNewProductMouseEntered
        lblBtnNewProduct.setBackground(enterColor);
    }//GEN-LAST:event_lblBtnNewProductMouseEntered

    private void lblBtnNewProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnNewProductMouseExited
        lblBtnNewProduct.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblBtnNewProductMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBtnNewProduct;
    private javax.swing.JLabel lblBtnRestock;
    // End of variables declaration//GEN-END:variables
}
