package view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Emanuel Hurt
 */
public class ProductRegistrationPanel extends javax.swing.JPanel {

    private boolean updateProduct;
    private Color enterColor;
    private Color exitColor;
    
    public ProductRegistrationPanel(boolean updateProduct, JPanel predecessor) {
        initComponents();
        this.updateProduct = updateProduct;
        enterColor = new Color(18,19,130);
        exitColor = new Color(26,115,182);
    }
    
    public JTextField getFieldCodProduct() {
        return fieldCodProduct;
    }

    public JTextField getFieldConcentration() {
        return fieldConcentration;
    }

    public JTextField getFieldDueDate() {
        return fieldDueDate;
    }

    public JTextField getFieldNumLote() {
        return fieldNumLote;
    }

    public JTextField getFieldPharmaForm() {
        return fieldPharmaForm;
    }

    public JTextField getFieldProductName() {
        return fieldProductName;
    }

    public JTextField getFieldPurchaseDate() {
        return fieldPurchaseDate;
    }

    public JTextField getFieldQuantity() {
        return fieldQuantity;
    }

    public JTextField getFieldTotalCostProduct() {
        return fieldTotalCostProduct;
    }

    public JTextField getFieldUnitPrice() {
        return fieldUnitPrice;
    }

    public JLabel getLblUnitCost() {
        return lblUnitCost;
    }

    public JLabel getLblBtnAcept() {
        return lblBtnAcept;
    }

    public JButton getBtnOk() {
        return btnOk;
    }
    
    public JComboBox getComBoxProvider() {
        return comBoxProvider;
    }
    
    public JLabel getLblSalePercentage() {
        return lblSalePercentage;
    }
    
    public JTextField getFieldGenericName() {
        return fieldGenericName;
    }
    
    public JTextArea getAreaDescription() {
        return areaDescription;
    }
    
    public boolean updateProduct() {
        return updateProduct;
    }
    
    public JLabel getErrorLbl() {
        return this.errorLbl;
    }

    public JLabel getBtnLblBack() {
        return this.btnLblBack;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        providerSubPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldPurchaseDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comBoxProvider = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDescription = new javax.swing.JTextArea();
        productsSubPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fieldProductName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldPharmaForm = new javax.swing.JTextField();
        fieldConcentration = new javax.swing.JTextField();
        fieldDueDate = new javax.swing.JTextField();
        fieldQuantity = new javax.swing.JTextField();
        fieldTotalCostProduct = new javax.swing.JTextField();
        lblUnitCost = new javax.swing.JLabel();
        fieldUnitPrice = new javax.swing.JTextField();
        lblBtnAcept = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fieldCodProduct = new javax.swing.JTextField();
        fieldNumLote = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblSalePercentage = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        fieldGenericName = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        errorLbl = new javax.swing.JLabel();
        btnLblBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));

        mainPanel.setBackground(new java.awt.Color(244, 244, 244));

        providerSubPanel.setBackground(new java.awt.Color(255, 255, 255));
        providerSubPanel.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nombre Proveedor:");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Fecha de Ingreso:");

        fieldPurchaseDate.setColumns(11);
        fieldPurchaseDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldPurchaseDateMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("PROVEEDOR Y FECHA DE INGRESO DEL PRODUCTO");

        comBoxProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("(*)");

        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("(*)");

        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setText("(*) Es campo obligatorio");

        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Detalle:");

        areaDescription.setColumns(20);
        areaDescription.setForeground(new java.awt.Color(51, 51, 51));
        areaDescription.setLineWrap(true);
        areaDescription.setRows(5);
        areaDescription.setWrapStyleWord(true);
        jScrollPane2.setViewportView(areaDescription);

        javax.swing.GroupLayout providerSubPanelLayout = new javax.swing.GroupLayout(providerSubPanel);
        providerSubPanel.setLayout(providerSubPanelLayout);
        providerSubPanelLayout.setHorizontalGroup(
            providerSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(providerSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(providerSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(providerSubPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBoxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(providerSubPanelLayout.createSequentialGroup()
                        .addGroup(providerSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(providerSubPanelLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(fieldPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28))
                    .addComponent(jLabel29)
                    .addComponent(jLabel32)
                    .addComponent(jScrollPane2))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        providerSubPanelLayout.setVerticalGroup(
            providerSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(providerSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(providerSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comBoxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(providerSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(38, 38, 38)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        productsSubPanel.setBackground(new java.awt.Color(255, 255, 255));
        productsSubPanel.setOpaque(false);

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre del Producto:");

        fieldProductName.setColumns(20);

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Forma Farmacéutica:");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Concentración:");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Fecha de Vencimiento:");

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Cantidad:");

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Costo Total de Compra:");

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Costo Unitario:");

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Precio Unitario:");

        fieldPharmaForm.setColumns(20);

        fieldConcentration.setColumns(15);

        fieldDueDate.setColumns(11);
        fieldDueDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldDueDateMouseClicked(evt);
            }
        });

        fieldQuantity.setColumns(5);

        fieldTotalCostProduct.setColumns(5);

        lblUnitCost.setForeground(new java.awt.Color(51, 51, 51));
        lblUnitCost.setText("..........");

        fieldUnitPrice.setColumns(5);

        lblBtnAcept.setBackground(new java.awt.Color(26, 115, 182));
        lblBtnAcept.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBtnAcept.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnAcept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnAcept.setText("ACEPTAR");
        lblBtnAcept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnAcept.setOpaque(true);
        lblBtnAcept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnAceptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnAceptMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Bs.");

        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Bs.");

        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Bs.");

        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Código del Producto:");

        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Número de Lote:");

        fieldCodProduct.setColumns(6);

        fieldNumLote.setColumns(15);

        btnOk.setText("ok");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("DATOS DEL PRODUCTO");

        lblSalePercentage.setForeground(new java.awt.Color(51, 51, 51));
        lblSalePercentage.setText("(+ X % para venta)");

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("(*)");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("(*)");

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("(*)");

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("(*)");

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("(*)");

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("(*)");

        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("(*)");

        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("(*)");

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("(*) Es campo obligatorio");

        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Nombre Genérico:");

        fieldGenericName.setColumns(20);

        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("(*)");

        errorLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 255, 255));
        errorLbl.setText("error");

        javax.swing.GroupLayout productsSubPanelLayout = new javax.swing.GroupLayout(productsSubPanel);
        productsSubPanel.setLayout(productsSubPanelLayout);
        productsSubPanelLayout.setHorizontalGroup(
            productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productsSubPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productsSubPanelLayout.createSequentialGroup()
                        .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productsSubPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldPharmaForm))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productsSubPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldGenericName))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productsSubPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel21)))
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22))
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldTotalCostProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUnitCost))
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSalePercentage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26))
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCodProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27))
                            .addGroup(productsSubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldNumLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE))))
            .addGroup(productsSubPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(lblBtnAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        productsSubPanelLayout.setVerticalGroup(
            productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(fieldGenericName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldPharmaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(fieldTotalCostProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17)
                    .addComponent(lblUnitCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18)
                    .addComponent(fieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalePercentage)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(fieldCodProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fieldNumLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBtnAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(providerSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productsSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(mainPanel);

        btnLblBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLblBack.setForeground(new java.awt.Color(51, 51, 51));
        btnLblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        btnLblBack.setText("Atrás");
        btnLblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLblBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLblBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDueDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldDueDateMouseClicked
        MyCalendar calendar = new MyCalendar(fieldDueDate);
    }//GEN-LAST:event_fieldDueDateMouseClicked

    private void lblBtnAceptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnAceptMouseEntered
        lblBtnAcept.setBackground(enterColor);
    }//GEN-LAST:event_lblBtnAceptMouseEntered

    private void lblBtnAceptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnAceptMouseExited
        lblBtnAcept.setBackground(exitColor);
    }//GEN-LAST:event_lblBtnAceptMouseExited

    private void fieldPurchaseDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPurchaseDateMouseClicked
        MyCalendar calendar = new MyCalendar(fieldPurchaseDate);
    }//GEN-LAST:event_fieldPurchaseDateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescription;
    private javax.swing.JLabel btnLblBack;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> comBoxProvider;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JTextField fieldCodProduct;
    private javax.swing.JTextField fieldConcentration;
    private javax.swing.JTextField fieldDueDate;
    private javax.swing.JTextField fieldGenericName;
    private javax.swing.JTextField fieldNumLote;
    private javax.swing.JTextField fieldPharmaForm;
    private javax.swing.JTextField fieldProductName;
    private javax.swing.JTextField fieldPurchaseDate;
    private javax.swing.JTextField fieldQuantity;
    private javax.swing.JTextField fieldTotalCostProduct;
    private javax.swing.JTextField fieldUnitPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBtnAcept;
    private javax.swing.JLabel lblSalePercentage;
    private javax.swing.JLabel lblUnitCost;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel productsSubPanel;
    private javax.swing.JPanel providerSubPanel;
    // End of variables declaration//GEN-END:variables
}
