package view;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author EmanuelHurt
 */
public class ProductsPanel extends javax.swing.JPanel {

    private InitialWindow containerWindow;
    
    public ProductsPanel(InitialWindow window) {
        containerWindow = window;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblBtnSearch = new javax.swing.JLabel();
        lblBtnSave = new javax.swing.JLabel();
        lblBtnDetails = new javax.swing.JLabel();
        lblBtnExport = new javax.swing.JLabel();
        txtFieldNameProduct = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(241, 242, 247));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        lblBtnSearch.setBackground(new java.awt.Color(26, 115, 182));
        lblBtnSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnSearch.setText("Buscar");
        lblBtnSearch.setOpaque(true);
        lblBtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnSearchMouseExited(evt);
            }
        });

        lblBtnSave.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnSave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnSave.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconSave.png"))); // NOI18N
        lblBtnSave.setText("Guardar");
        lblBtnSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnSave.setOpaque(true);

        lblBtnDetails.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnDetails.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnDetails.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconDetails.png"))); // NOI18N
        lblBtnDetails.setText("Detalles");
        lblBtnDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnDetails.setOpaque(true);

        lblBtnExport.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnExport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnExport.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnExport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconExport.png"))); // NOI18N
        lblBtnExport.setText("Exportar");
        lblBtnExport.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnExport.setOpaque(true);

        txtFieldNameProduct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFieldNameProduct.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFieldNameProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(lblBtnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBtnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBtnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBtnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 276;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 21, 0, 18);
        add(jPanel1, gridBagConstraints);

        productsTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "COD", "PROVEEDOR", "NOMBRE", "NOM GENÉRICO", "FORMA FARMACÉUTICA", "CONCENTRACIÓN", "PRECIO UNITARIO", "SALDO", "VENCIMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 875;
        gridBagConstraints.ipady = 366;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 21, 28, 18);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnSearchMouseEntered
        lblBtnSearch.setBackground(new Color(18,19,130));
    }//GEN-LAST:event_lblBtnSearchMouseEntered

    private void lblBtnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnSearchMouseExited
        lblBtnSearch.setBackground(new Color(26,115,182));
    }//GEN-LAST:event_lblBtnSearchMouseExited

    public JTable getProductsTable() {
        return productsTable;
    }

    public JLabel getLblBtnSave() {
        return lblBtnSave;
    }
    
    public JLabel getLblBtnDetails() {
        return lblBtnDetails;
    }
    
    public JLabel getLblBtnExport() {
        return lblBtnExport;
    }

    public JLabel getLblBtnSearch() {
        return lblBtnSearch;
    }

    public JTextField getTxtFieldNameProduct() {
        return txtFieldNameProduct;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBtnDetails;
    private javax.swing.JLabel lblBtnExport;
    private javax.swing.JLabel lblBtnSave;
    private javax.swing.JLabel lblBtnSearch;
    private javax.swing.JTable productsTable;
    private javax.swing.JTextField txtFieldNameProduct;
    // End of variables declaration//GEN-END:variables
}
