package view;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author EmanuelHurt
 */
public class ProductsPanel extends javax.swing.JPanel {

    private InitialWindow containerWindow;
    
    public ProductsPanel(InitialWindow window) {
        containerWindow = window;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBtnSearch = new javax.swing.JLabel();
        txtFieldNameProduct = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        lblBtnExport = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBtnSearch.setBackground(new java.awt.Color(26, 115, 182));
        lblBtnSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnSearch.setText("Buscar");
        lblBtnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnSearch.setOpaque(true);
        lblBtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnSearchMouseExited(evt);
            }
        });
        jPanel1.add(lblBtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 10, 55, 32));

        txtFieldNameProduct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFieldNameProduct.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtFieldNameProduct.setMaximumSize(new java.awt.Dimension(64, 21));
        jPanel1.add(txtFieldNameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, 367, 32));

        productsTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "COD", "PROVEEDOR", "NOMBRE", "NOM GENÉRICO", "FORMA FARMACÉUTICA", "CONCENTRACIÓN", "PRECIO UNITARIO", "SALDO", "VENCIMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(productsTable);

        lblBtnExport.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnExport.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnExport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconExport.png"))); // NOI18N
        lblBtnExport.setText("Exportar");
        lblBtnExport.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        lblBtnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnExport.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(lblBtnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBtnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnSearchMouseEntered
        lblBtnSearch.setBackground(new Color(18,19,130));
    }//GEN-LAST:event_lblBtnSearchMouseEntered

    private void lblBtnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnSearchMouseExited
        lblBtnSearch.setBackground(new Color(26,115,182));
    }//GEN-LAST:event_lblBtnSearchMouseExited

    public JTable getProductsTable() {
        return productsTable;
    }
     
    public JLabel getLblBtnExport() {
        return lblBtnExport;
    }

    public JLabel getLblBtnSearch() {
        return lblBtnSearch;
    }

    public JTextField getTxtFieldNameProduct() {
        return txtFieldNameProduct;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBtnExport;
    private javax.swing.JLabel lblBtnSearch;
    private javax.swing.JTable productsTable;
    private javax.swing.JTextField txtFieldNameProduct;
    // End of variables declaration//GEN-END:variables
}
