package view;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author EmanuelHurt
 */
public class ProvidersPanel extends javax.swing.JPanel {

    private Color enterColor, exitColor;
    
    public ProvidersPanel() {
        initComponents();
        enterColor = new Color(18,19,130);
        exitColor = new Color(26,115,182);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldNameProvider = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        lblBtnRegister = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProvidersTable = new javax.swing.JTable();
        lblBtnDeleteProvider = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("REGISTRAR NUEVO PROVEEDOR");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("(*) Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 6, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel5.setText("(*) campo obligatorio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        fieldNameProvider.setBackground(new java.awt.Color(255, 255, 255));
        fieldNameProvider.setColumns(25);
        fieldNameProvider.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldNameProvider.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 299;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 6, 0, 19);
        jPanel1.add(fieldNameProvider, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 42, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        fieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        fieldEmail.setColumns(15);
        fieldEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldEmail.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 179;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        jPanel1.add(fieldEmail, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("telf/cel:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 29, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        fieldPhone.setBackground(new java.awt.Color(255, 255, 255));
        fieldPhone.setColumns(10);
        fieldPhone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldPhone.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        jPanel1.add(fieldPhone, gridBagConstraints);

        lblBtnRegister.setBackground(new java.awt.Color(26, 115, 182));
        lblBtnRegister.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnRegister.setText("Guardar");
        lblBtnRegister.setOpaque(true);
        lblBtnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnRegisterMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 32, 41, 0);
        jPanel1.add(lblBtnRegister, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("LISTA DE PROVEEDORES");

        ProvidersTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ProvidersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "Nombre", "email", "Telf/Cel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProvidersTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProvidersTable);

        lblBtnDeleteProvider.setBackground(new java.awt.Color(204, 204, 204));
        lblBtnDeleteProvider.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnDeleteProvider.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnDeleteProvider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnDeleteProvider.setText("Eliminar");
        lblBtnDeleteProvider.setOpaque(true);
        lblBtnDeleteProvider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnDeleteProviderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnDeleteProviderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblBtnDeleteProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBtnDeleteProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnRegisterMouseEntered
        lblBtnRegister.setBackground(enterColor);
    }//GEN-LAST:event_lblBtnRegisterMouseEntered

    private void lblBtnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnRegisterMouseExited
        lblBtnRegister.setBackground(exitColor);
    }//GEN-LAST:event_lblBtnRegisterMouseExited

    private void lblBtnDeleteProviderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnDeleteProviderMouseEntered
        this.lblBtnDeleteProvider.setBackground(new Color(255,102,102));
        this.lblBtnDeleteProvider.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblBtnDeleteProviderMouseEntered

    private void lblBtnDeleteProviderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnDeleteProviderMouseExited
        this.lblBtnDeleteProvider.setBackground(new Color(204,204,204));
        this.lblBtnDeleteProvider.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_lblBtnDeleteProviderMouseExited

    public JTextField getFieldEmail() {
        return fieldEmail;
    }

    public JTextField getFieldNameProvider() {
        return fieldNameProvider;
    }

    public JTextField getFieldPhone() {
        return fieldPhone;
    }

    public JLabel getLblBtnRegister() {
        return lblBtnRegister;
    }   

    public JTable getProvidersTable() {
        return ProvidersTable;
    }
    
    public JLabel getLblBtnDeleteProvider() {
        return lblBtnDeleteProvider;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProvidersTable;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNameProvider;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBtnDeleteProvider;
    private javax.swing.JLabel lblBtnRegister;
    // End of variables declaration//GEN-END:variables
}
