package view;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author EmanuelHurt
 */
public class QuestionModal extends javax.swing.JPanel {

    private JDialog modalFrame;
    
    public QuestionModal(String message) {
        initComponents();
        
        lblMenssage.setText(message);
        
        modalFrame = new JDialog();
        modalFrame.add(this);
        modalFrame.setModal(true);
        modalFrame.pack();
        modalFrame.setLocationRelativeTo(null);
        modalFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMenssage = new javax.swing.JLabel();
        lblBtnOk = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconQuestion.png"))); // NOI18N

        lblMenssage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMenssage.setForeground(new java.awt.Color(51, 51, 51));
        lblMenssage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenssage.setText("No hay resultados para el producto productito");

        lblBtnOk.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnOk.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblBtnOk.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnOk.setText("Ok");
        lblBtnOk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnOk.setOpaque(true);
        lblBtnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenssage, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(lblBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMenssage)
                .addGap(18, 18, 18)
                .addComponent(lblBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnOkMouseClicked
        modalFrame.dispose();
    }//GEN-LAST:event_lblBtnOkMouseClicked

    public JLabel getLblMenssage() {
        return lblMenssage;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBtnOk;
    private javax.swing.JLabel lblMenssage;
    // End of variables declaration//GEN-END:variables
}
