package view;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author EmanuelHurt
 */
public class SaleHistoryModal extends javax.swing.JPanel {

    private JDialog modalFrame;
    
    public SaleHistoryModal() {
        initComponents();
    }

    public JTable getTblSaleDetail() {
        return tblSaleDetail;
    }
    
    public void showSaleDetailModal() {
        modalFrame = new JDialog();
        modalFrame.setUndecorated(true);
        modalFrame.setModal(true);
        modalFrame.add(this);      
        modalFrame.pack();
        modalFrame.setLocationRelativeTo(null);
        modalFrame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHour = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblClient = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaleDetail = new javax.swing.JTable();
        lblHour2 = new javax.swing.JLabel();
        lblTotalMount = new javax.swing.JLabel();
        lblBtnOk = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        lblHour.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHour.setForeground(new java.awt.Color(51, 51, 51));
        lblHour.setText("08:05:12");

        lblDate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(51, 51, 51));
        lblDate.setText("2024-04-30");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Cliente:");

        lblClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblClient.setForeground(new java.awt.Color(51, 51, 51));
        lblClient.setText("Sr. Perez");

        tblSaleDetail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblSaleDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROVEEDOR", "PRODUCTO", "FORMA", "UNIDADES", "MONTO (Bs.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSaleDetail);

        lblHour2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHour2.setForeground(new java.awt.Color(51, 51, 51));
        lblHour2.setText("MONTO TOTAL: Bs.");

        lblTotalMount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTotalMount.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalMount.setText("..............");

        lblBtnOk.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnOk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnOk.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnOk.setText("OK");
        lblBtnOk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnOk.setOpaque(true);
        lblBtnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblClient)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHour)
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHour2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalMount)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(lblBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHour)
                    .addComponent(lblDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHour2)
                    .addComponent(lblTotalMount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnOkMouseClicked
        modalFrame.dispose();
    }//GEN-LAST:event_lblBtnOkMouseClicked

    public JLabel getLblTotalMount() {
        return lblTotalMount;
    }
    
    public JLabel getLblClient() {
        return lblClient;
    }

    public JLabel getLblDate() {
        return lblDate;
    }

    public JLabel getLblHour() {
        return lblHour;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBtnOk;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblHour2;
    private javax.swing.JLabel lblTotalMount;
    private javax.swing.JTable tblSaleDetail;
    // End of variables declaration//GEN-END:variables
}
