package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Product;

import controller.ProductSaleController;
import java.awt.Color;
import javax.swing.JDialog;
import model.ProductSale;
/**
 *
 * @author EmanuelHurt
 */
public class SalePanel extends javax.swing.JPanel {

    private final ProductSaleController saleController;
    private final JDialog modalFrame;
    private final Product product;
    private final double percentageDiscount;
    private double priceDiscount;
    
    public SalePanel(double percenDiscount, Product prod, ProductSaleController saleController) {
        initComponents();
              
        
        lblAlert.setForeground(Color.WHITE);
        
        this.lblTotalPrice.setText("");
        
        this.product = prod;
        
        this.saleController = saleController;       
        
        lblProductName.setText(product.getNameProduct());
        lblProductExistence.setText(product.getExistence()+"");
        lblPriceUnit.setText(product.getPrice() + "");
        
        //PRESENTACION DEL checkBoxDiscount
        percentageDiscount = percenDiscount;
        
        String sDiscount = percentageDiscount + "% descuento: Bs.";
        this.lblDiscountPercentage.setText(sDiscount);
        //PRESENTACION DEL checkBoxDiscountPrice
        priceDiscount = product.getPrice() - (percentageDiscount/100.0 * product.getPrice());
        priceDiscount = Math.round(priceDiscount * Math.pow(10, 2)) / Math.pow(10, 2);
        checkBoxDiscountPrice.setText(priceDiscount + "");
        checkBoxDiscountPrice.setEnabled(false);
        
        this.modalFrame = new JDialog();
        this.modalFrame.setModal(true);
        this.modalFrame.setUndecorated(true);
        this.modalFrame.add(this);
        this.modalFrame.pack();
        this.modalFrame.setLocationRelativeTo(null);
        this.modalFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPriceUnit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldQuantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblProductExistence = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAlert = new javax.swing.JLabel();
        lblDiscountPercentage = new javax.swing.JLabel();
        checkBoxDiscountPrice = new javax.swing.JCheckBox();
        btnSale = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("VENTA DE PRODUCTO");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Producto:");

        lblProductName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(51, 51, 51));
        lblProductName.setText("nombre del producto");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Precio Unitario:");

        lblPriceUnit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPriceUnit.setForeground(new java.awt.Color(51, 51, 51));
        lblPriceUnit.setText("............");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Cantidad:");

        fieldQuantity.setColumns(4);
        fieldQuantity.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fieldQuantity.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Precio Total:");

        lblTotalPrice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalPrice.setText(".........");

        btnOk.setBackground(new java.awt.Color(0, 153, 255));
        btnOk.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnOk.setForeground(new java.awt.Color(0, 0, 0));
        btnOk.setText("Ok");
        btnOk.setOpaque(true);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Bs.");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Bs.");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Saldo Producto:");

        lblProductExistence.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProductExistence.setForeground(new java.awt.Color(51, 51, 51));
        lblProductExistence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductExistence.setText("jLabel12");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("unidades");

        lblAlert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAlert.setForeground(new java.awt.Color(255, 51, 51));
        lblAlert.setText("SALDO EXCEDIDO");

        lblDiscountPercentage.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblDiscountPercentage.setForeground(new java.awt.Color(51, 51, 51));
        lblDiscountPercentage.setText("X % descuento: Bs.");

        checkBoxDiscountPrice.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        checkBoxDiscountPrice.setForeground(new java.awt.Color(51, 51, 51));
        checkBoxDiscountPrice.setText("10.11");
        checkBoxDiscountPrice.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        checkBoxDiscountPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDiscountPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProductName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalPrice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblAlert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPriceUnit)
                        .addGap(35, 35, 35)
                        .addComponent(lblDiscountPercentage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxDiscountPrice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProductExistence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblProductName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblProductExistence)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblPriceUnit)
                    .addComponent(lblDiscountPercentage)
                    .addComponent(checkBoxDiscountPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk)
                    .addComponent(lblAlert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalPrice))
                .addGap(134, 134, 134))
        );

        btnSale.setBackground(new java.awt.Color(0, 153, 255));
        btnSale.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSale.setForeground(new java.awt.Color(255, 255, 255));
        btnSale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSale.setText("Confirmar");
        btnSale.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        btnSale.setOpaque(true);
        btnSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaleMouseClicked(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(51, 51, 51));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnSale, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSale, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaleMouseClicked
        if (!fieldQuantity.getText().isEmpty() && !lblTotalPrice.getText().isEmpty()) {
            
            ProductSale productSale = new ProductSale();
            
            int quantity = Integer.parseInt(fieldQuantity.getText());
            productSale.setQuantity(quantity);
            double totalPrice = Double.parseDouble(lblTotalPrice.getText());
            productSale.setTotalPrice(totalPrice);
            productSale.setIdProduct(product.getIdProduct());
            productSale.setCodProduct(product.getCodProduct());
            
            //PASARLO AL ARRAYLIST DEL CONTROLADOR
            saleController.getProductsSaleList().add(productSale);
            //INDICAR AL CONTROLADOR QUE AGREGUE EL PRODUCTO AL PANEL LISTA
            saleController.addProductSaleToPanel(productSale, product);
            
            modalFrame.dispose();
        }
    }//GEN-LAST:event_btnSaleMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        modalFrame.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    //CALCULA EL MONTO DEL PRODUCTO A VENDER
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        
        try {
            double quantity = Double.parseDouble(fieldQuantity.getText());
            if (quantity <= product.getExistence()) {
                lblAlert.setForeground(Color.WHITE);
                double price = Double.parseDouble(lblPriceUnit.getText());
                double totalPrice = quantity * price;
                totalPrice = Math.round(totalPrice * Math.pow(10, 2)) / Math.pow(10, 2);
                lblTotalPrice.setText(totalPrice + "");
                
                checkBoxDiscountPrice.setEnabled(true);
                
            } else {
                lblAlert.setForeground(Color.RED);
                lblTotalPrice.setText("");
            }
        }catch(NumberFormatException ex) {
            ErrorModal errorModal = new ErrorModal("El campo cantidad debe contener un valor numérico");
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void checkBoxDiscountPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDiscountPriceActionPerformed
        double quantity = Double.parseDouble(fieldQuantity.getText());
        if (checkBoxDiscountPrice.isSelected()) {
            double discountPrice = Double.parseDouble(checkBoxDiscountPrice.getText());
            quantity = Double.parseDouble(fieldQuantity.getText());
            double totalPrice = quantity * discountPrice;
            totalPrice = Math.round(totalPrice * Math.pow(10, 2)) / Math.pow(10, 2);
            lblTotalPrice.setText(""+totalPrice);
        }
        else {
            double price = Double.parseDouble(lblPriceUnit.getText());
            double totalPrice = quantity * price;
            totalPrice = Math.round(totalPrice * Math.pow(10, 2)) / Math.pow(10, 2);
            lblTotalPrice.setText(totalPrice + "");
        }
    }//GEN-LAST:event_checkBoxDiscountPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel btnSale;
    private javax.swing.JCheckBox checkBoxDiscountPrice;
    private javax.swing.JTextField fieldQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlert;
    private javax.swing.JLabel lblDiscountPercentage;
    private javax.swing.JLabel lblPriceUnit;
    private javax.swing.JLabel lblProductExistence;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblTotalPrice;
    // End of variables declaration//GEN-END:variables
}
