package view;

/**
 *
 * @author EmanuelHurt
 */

import controller.ProductSaleController;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

public class SearchProductPanel extends javax.swing.JPanel {
    
    private ProductSaleController saleController;
    
    public SearchProductPanel() {
        initComponents();
    }

    public JPanel getProductsSaleListPanel() {
        return ProductsSaleListPanel;
    }

    public JLabel getBtnSearch() {
        return btnSearch;
    }   
    
    public JTextField getSearchField() {
        return SearchField;
    }
    
    public JTable getTableProductsFound() {
        return tableProductsFound;
    }
    
    public JLabel getLblTotalAmount() {
        return lblTotalAmount;
    }
    
    public JLabel getlblBtnMakeSale() {
        return lblBtnMakeSale;
    }
    
    public void setController(ProductSaleController saleController) {
        this.saleController = saleController;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableProductsFound = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductsSaleListPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        lblBtnMakeSale = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        btnSearch.setBackground(new java.awt.Color(26, 115, 182));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch.setText("Buscar");
        btnSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        btnSearch.setOpaque(true);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });

        SearchField.setBackground(new java.awt.Color(255, 255, 255));
        SearchField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SearchField.setForeground(new java.awt.Color(51, 51, 51));
        SearchField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 445;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 23);
        add(jPanel1, gridBagConstraints);

        tableProductsFound.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableProductsFound.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "COD", "PROVEEDOR", "PRODUCTO", "NOM GENÉRICO", "FORMA FARMACÉUTICA", "CONCENTRACIÓN", "PRECIO", "SALDO PRODUCTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProductsFound.getTableHeader().setReorderingAllowed(false);
        tableProductsFound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductsFoundMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableProductsFound);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 564;
        gridBagConstraints.ipady = 370;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 14, 0);
        add(jScrollPane6, gridBagConstraints);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        ProductsSaleListPanel.setBackground(new java.awt.Color(255, 255, 255));
        ProductsSaleListPanel.setLayout(new java.awt.GridLayout(50, 1, 0, 4));
        jScrollPane1.setViewportView(ProductsSaleListPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 284;
        gridBagConstraints.ipady = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 20, 0, 23);
        add(jScrollPane1, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE VENTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 23);
        add(jLabel1, gridBagConstraints);

        lblTotalAmount.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalAmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalAmount.setText("Monto Total: Bs.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 23);
        add(lblTotalAmount, gridBagConstraints);

        lblBtnMakeSale.setBackground(new java.awt.Color(26, 115, 182));
        lblBtnMakeSale.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBtnMakeSale.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnMakeSale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnMakeSale.setText("REALIZAR VENTA");
        lblBtnMakeSale.setOpaque(true);
        lblBtnMakeSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnMakeSaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnMakeSaleMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 100, 0, 0);
        add(lblBtnMakeSale, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel2.setText("---");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 170, 0, 0);
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void tableProductsFoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductsFoundMouseClicked
        if (evt.getClickCount() == 2) {
            int row = tableProductsFound.getSelectedRow();
            if (saleController != null) {
                saleController.showSalesPanelForSelectedProduct(row);
            }
        }
    }//GEN-LAST:event_tableProductsFoundMouseClicked

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        btnSearch.setBackground(new Color(18,19,130));
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        btnSearch.setBackground(new Color(26,115,182));
    }//GEN-LAST:event_btnSearchMouseExited

    private void lblBtnMakeSaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMakeSaleMouseEntered
        lblBtnMakeSale.setBackground(new Color(18,19,130));
    }//GEN-LAST:event_lblBtnMakeSaleMouseEntered

    private void lblBtnMakeSaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMakeSaleMouseExited
        lblBtnMakeSale.setBackground(new Color(26,115,182));
    }//GEN-LAST:event_lblBtnMakeSaleMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProductsSaleListPanel;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblBtnMakeSale;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTable tableProductsFound;
    // End of variables declaration//GEN-END:variables
}
