package view;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author EmanuelHurt
 */
public class SuccessModal extends javax.swing.JPanel {

    private JDialog modalFrame;
    
    public SuccessModal(String message) {
        initComponents();
        
        lblMessage.setText(message);
        
        modalFrame = new JDialog();
        modalFrame.setModal(true);
        modalFrame.add(this);        
        modalFrame.pack();
        modalFrame.setLocationRelativeTo(null);
        modalFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblBtnOk = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconVerificado.png"))); // NOI18N

        lblMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(51, 51, 51));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Producto registrado exitosamente");

        lblBtnOk.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnOk.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblBtnOk.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnOk.setText("Ok");
        lblBtnOk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnOk.setOpaque(true);
        lblBtnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(lblBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addComponent(lblMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage)
                .addGap(18, 18, 18)
                .addComponent(lblBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnOkMouseClicked
        modalFrame.dispose();
    }//GEN-LAST:event_lblBtnOkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBtnOk;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
