package view;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author EmanuelHurt
 */
public class TableDetailsModal extends javax.swing.JPanel {

    private JDialog modalFrame;
    
    public TableDetailsModal() {
        initComponents();
    }

    public void show() {
        modalFrame = new JDialog();
        modalFrame.setModal(true);
        modalFrame.add(this);        
        modalFrame.pack();
        modalFrame.setLocationRelativeTo(null);
        modalFrame.setVisible(true);
    }
    
    public JTable getTblDetails() {
        return tblDetails;
    }
    
    public JLabel getlblBtnOk() {
        return lblBtnOk;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        lblBtnOk = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        tblDetails.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad Total de Productos", "Costo Total de Compra (Bs.)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDetails);

        lblBtnOk.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnOk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnOk.setForeground(new java.awt.Color(51, 51, 51));
        lblBtnOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnOk.setText("OK");
        lblBtnOk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lblBtnOk.setOpaque(true);
        lblBtnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lblBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnOkMouseClicked
        modalFrame.dispose();
    }//GEN-LAST:event_lblBtnOkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBtnOk;
    private javax.swing.JTable tblDetails;
    // End of variables declaration//GEN-END:variables
}
