package view;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author EmanuelHurt
 */
public class UserManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserManagementPanel
     */
    public UserManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBtnShowUsers = new javax.swing.JLabel();
        lblBtnAddUser = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Gestión de Usuarios");

        lblBtnShowUsers.setBackground(new java.awt.Color(26, 115, 182));
        lblBtnShowUsers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnShowUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnShowUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnShowUsers.setText("Ver lista de Usuarios");
        lblBtnShowUsers.setOpaque(true);
        lblBtnShowUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnShowUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnShowUsersMouseExited(evt);
            }
        });

        lblBtnAddUser.setBackground(new java.awt.Color(26, 115, 182));
        lblBtnAddUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnAddUser.setText("Agregar Usuario");
        lblBtnAddUser.setOpaque(true);
        lblBtnAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnAddUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnAddUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBtnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBtnShowUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBtnShowUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBtnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnShowUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnShowUsersMouseEntered
        lblBtnShowUsers.setBackground(new Color(18,19,130));
    }//GEN-LAST:event_lblBtnShowUsersMouseEntered

    private void lblBtnShowUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnShowUsersMouseExited
        lblBtnShowUsers.setBackground(new Color(26,115,182));
    }//GEN-LAST:event_lblBtnShowUsersMouseExited

    private void lblBtnAddUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnAddUserMouseEntered
        lblBtnAddUser.setBackground(new Color(18,19,130));
    }//GEN-LAST:event_lblBtnAddUserMouseEntered

    private void lblBtnAddUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnAddUserMouseExited
        lblBtnAddUser.setBackground(new Color(26,115,182));
    }//GEN-LAST:event_lblBtnAddUserMouseExited

    public JLabel getLblBtnShowUsers() {
        return lblBtnShowUsers;
    }

    public JLabel getLblBtnAddUser() {
        return lblBtnAddUser;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBtnAddUser;
    private javax.swing.JLabel lblBtnShowUsers;
    // End of variables declaration//GEN-END:variables
}
